[project]
name = "epic-events"
version = "0.1.0"
description = "A C.R.M. for the company Epic Events (with a C.L.I.)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "bcrypt>=4.3.0",
    "email-validator>=2.3.0",
    "psycopg>=3.2.9",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "sentry-sdk>=2.35.1",
    "sqlalchemy>=2.0.43",
    "typer>=0.16.1",
]
