[project]
name = "epic-events"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "bcrypt>=4.3.0",
    "email-validator>=2.3.0",
    "phonenumbers>=9.0.13",
    "psycopg2-binary>=2.9.10",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "rich-argparse>=1.7.1",
    "sqlalchemy>=2.0.43",
]
