name: tests-and-coverage

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COV_MIN: "80"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync env from lockfile
        run: uv sync --frozen

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest -q
          uv run coverage report
          uv run coverage xml -o coverage.xml
          uv run coverage html

      - name: Install genbadge
        run: uv add genbadge

      - name: Generate coverage badge
        run: |
          uv run genbadge coverage -i coverage.xml -o coverage.svg

      - name: Enforce coverage threshold
        id: covcheck
        run: |
          python - <<'PY'
          import sys, xml.etree.ElementTree as ET, os
          rate = float(ET.parse('coverage.xml').getroot().get('line-rate', 0.0)) * 100
          min_rate = float(os.environ.get("COV_MIN","0"))
          print(f"Coverage: {rate:.2f}% (min {min_rate:.2f}%)")
          # Expose pour étapes suivantes
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"pct={rate:.2f}\n")
          if rate < min_rate:
              sys.exit(1)
          PY
  
      - name: Comment PR with coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pct = core.getInput('pct', { required: false }) || '${{ steps.covcheck.outputs.pct }}';
            const body = `**Coverage:** ${pct}%  \n(Generated by CI from \`coverage.xml\`)`;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const marker = '<!-- coverage-sticky -->';
            const previous = comments.find(c => c.body && c.body.includes(marker));
            if (previous) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: previous.id,
                body: `${marker}\n${body}`
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `${marker}\n${body}`
              });
            }

      - name: Commit coverage badge
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add coverage.svg
          git commit -m "ci: update coverage badge" || echo "No badge changes"
          git push

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/
          if-no-files-found: warn
